#!/usr/bin/env bash
# netj's bash configuration
# Author: Jaeho Shin <netj@sparcs.kaist.ac.kr>
# Created: 2000-10-20
# Reformed: 2004-05-28
# Second-Reform: 2012-02-24

# load bpm first
. ~/.bash/plugins/bpm.sh

# load local configuration and modules
for s in ~/.bash_local
do ! [ -r $s ] || . $s
done

# Uncomment below to enable bash completion.
# Command to install: brew install bash-completion

# if [ -f $(brew --prefix)/etc/bash_completion ]; then
#   . $(brew --prefix)/etc/bash_completion
# fi

# vim:et:ts=4:sw=4:sts=4
